spring:
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: "local"
server:
  port: 57777
logging:
  level:
    org:
      hibernate:
        SQL:  DEBUG
---
spring:
  profiles: local
  datasource:
    url:  jdbc:mysql://localhost:3306/catalogo
    username: catalogoOwner
    password: 3Gj5L84sLe5DL0ns
 
---
spring:
  profiles: dev
  datasource:
    url:  jdbc:mysql://mysql:3306/catalogo
    username: catalogoOwner
    password: 3Gj5L84sLe5DL0ns
  
---
spring:
  profiles: prd
  datasource:
    url:  jdbc:mysql://mysql:3306/catalogo
    username: catalogoOwner
    password: 3Gj5L84sLe5DL0ns
  